Changing order of detection of packages

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -492,7 +492,6 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all CoinUtils"
-ac_subdirs_all="$ac_subdirs_all Alps"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Blas"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Lapack"
 ac_subdirs_all="$ac_subdirs_all ThirdParty/Glpk"
@@ -500,6 +499,7 @@ ac_subdirs_all="$ac_subdirs_all Data/Sample"
 ac_subdirs_all="$ac_subdirs_all Osi"
 ac_subdirs_all="$ac_subdirs_all Clp"
 ac_subdirs_all="$ac_subdirs_all Cgl"
+ac_subdirs_all="$ac_subdirs_all Alps"
 ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX MPICXX ADD_FFLAGS DBG_FFLAGS OPT_FFLAGS F77 FFLAGS ac_ct_F77 MPIF77 EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS PKG_CONFIG ac_pt_PKG_CONFIG COIN_HAS_PKGCONFIG_TRUE COIN_HAS_PKGCONFIG_FALSE COIN_PKG_CONFIG_PATH COIN_PKG_CONFIG_PATH_UNINSTALLED COIN_SKIP_PROJECTS subdirs LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
@@ -1161,9 +1161,6 @@ Optional Packages:
   --with-coinutils-datadir
                           directory with data files for using project
                           CoinUtils
-  --with-alps-lib linker flags for using project Alps
-  --with-alps-incdir directory with header files for using project Alps
-  --with-alps-datadir directory with data files for using project Alps
   --with-blas-lib linker flags for using project Blas
   --with-blas-incdir directory with header files for using project Blas
   --with-blas-datadir directory with data files for using project Blas
@@ -1187,6 +1184,9 @@ Optional Packages:
   --with-cgl-lib linker flags for using project Cgl
   --with-cgl-incdir directory with header files for using project Cgl
   --with-cgl-datadir directory with data files for using project Cgl
+  --with-alps-lib linker flags for using project Alps
+  --with-alps-incdir directory with header files for using project Alps
+  --with-alps-datadir directory with data files for using project Alps
 
 Some influential environment variables:
   CDEFS       Additional -D flags to be used when compiling C code.
@@ -5917,7 +5917,7 @@ else
 fi
 full_prefix=`cd $full_prefix ; pwd`
 
-abs_lib_dir=$full_prefix/lib
+abs_lib_dir=$full_prefix/lib/coin
 
 abs_include_dir=$full_prefix/include
 
@@ -20782,7 +20782,7 @@ if test $enable_shared = yes; then
     *-linux-*)
       if test "$GXX" = "yes"; then
         RPATH_FLAGS=
-        for dir in $abs_lib_dir/coin $abs_lib_dir/coin/ThirdParty; do
+        for dir in $abs_lib_dir $abs_lib_dir/ThirdParty; do
           RPATH_FLAGS="$RPATH_FLAGS -Wl,--rpath -Wl,$dir"
         done
       fi ;;
@@ -20799,7 +20799,7 @@ if test $enable_shared = yes; then
         RPATH_FLAGS=nothing ;;
     *-*-solaris*)
         RPATH_FLAGS=
-        for dir in $abs_lib_dir/coin $abs_lib_dir/coin/ThirdParty; do
+        for dir in $abs_lib_dir $abs_lib_dir/ThirdParty; do
           RPATH_FLAGS="$RPATH_FLAGS -R$dir"
         done
   esac
@@ -21032,7 +21032,11 @@ COIN_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
 # let's assume that when installing into $prefix, then the user may have installed some other coin projects there before, so it's worth to have a look into there
 # best would actually to use ${libdir}, since .pc files get installed into ${libdir}/pkgconfig,
 # unfortunately, ${libdir} expands to ${exec_prefix}/lib and ${exec_prefix} to ${prefix}...
-COIN_PKG_CONFIG_PATH="${prefix}/lib/pkgconfig:${COIN_PKG_CONFIG_PATH}"
+if test "x${prefix}" = xNONE ; then
+  COIN_PKG_CONFIG_PATH="${ac_default_prefix}/lib/pkgconfig:${COIN_PKG_CONFIG_PATH}"
+else
+  COIN_PKG_CONFIG_PATH="${prefix}/lib/pkgconfig:${COIN_PKG_CONFIG_PATH}"
+fi
 
 
 # Check whether --with-coin-instdir or --without-coin-instdir was given.
@@ -21183,123 +21187,6 @@ echo "${ECHO_T}yes" >&6
 
 
 subdirs="$subdirs CoinUtils"
-
-  else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  fi
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-
-echo "$as_me:$LINENO: checking whether project Alps is available" >&5
-echo $ECHO_N "checking whether project Alps is available... $ECHO_C" >&6
-
-coin_has_alps=notGiven
-coin_have_project_dir=no
-
-# check if user wants to skip project in any case
-
-if test x"$COIN_SKIP_PROJECTS" != x; then
-  for dir in $COIN_SKIP_PROJECTS; do
-    if test $dir = "Alps"; then
-      coin_has_alps=skipping
-    fi
-    if test $dir = "/Alps"; then
-      coin_has_alps=skipping
-    fi
-  done
-fi
-
-if test $coin_has_alps != skipping; then
-  if test $PACKAGE_TARNAME = alps; then
-    coin_has_alps=.
-    coin_have_project_dir=yes
-  fi
-
-
-# Check whether --with-m4_tolower(Alps)-lib or --without-m4_tolower(Alps)-lib was given.
-if test "${with_alps_lib+set}" = set; then
-  withval="$with_alps_lib"
-  coin_has_alps=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Alps)-incdir or --without-m4_tolower(Alps)-incdir was given.
-if test "${with_alps_incdir+set}" = set; then
-  withval="$with_alps_incdir"
-  coin_has_alps=installed
-fi;
-
-
-# Check whether --with-m4_tolower(Alps)-datadir or --without-m4_tolower(Alps)-datadir was given.
-if test "${with_alps_datadir+set}" = set; then
-  withval="$with_alps_datadir"
-  coin_has_alps=installed
-fi;
-
-
-
-
-
-fi
-
-if test $coin_has_alps = notGiven; then
-  #check for project by using pkg-config, if pkg-config is available
-  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
-  if test -n "$PKG_CONFIG" ; then
-    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
-    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
-
-if test -n "$PKG_CONFIG" ; then
-  if $PKG_CONFIG --exists "alps"; then
-    ALPS_VERSION=`$PKG_CONFIG --modversion "alps" 2>/dev/null`
-    coin_has_alps="$ALPS_VERSION"
-  else
-    ALPS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "alps"`
-
-  fi
-else
-  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Alps without pkg-config\"" >&5
-echo "$as_me: error: \"Cannot check for existance of module Alps without pkg-config\"" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
-    export PKG_CONFIG_PATH
-  fi
-fi
-
-# if not found yet, check if project is available in present directory
-if test "$coin_has_alps" = notGiven; then
-  if test -d $srcdir//Alps; then
-    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
-    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
-    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
-     coin_have_project_dir=yes
-
-    if test $coin_have_project_dir = yes; then
-      coin_has_alps=Alps
-    fi
-  fi
-fi
-
-echo "$as_me:$LINENO: result: $coin_has_alps" >&5
-echo "${ECHO_T}$coin_has_alps" >&6
-
-echo "$as_me:$LINENO: checking whether project Alps need to be configured" >&5
-echo $ECHO_N "checking whether project Alps need to be configured... $ECHO_C" >&6
-if test "$coin_have_project_dir" = yes ; then
-
-  if test -r $srcdir/Alps/configure; then
-    coin_subdirs="$coin_subdirs Alps"
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-
-
-subdirs="$subdirs Alps"
 
   else
     echo "$as_me:$LINENO: result: no" >&5
@@ -22154,6 +22041,123 @@ echo "${ECHO_T}yes" >&6
 
 
 subdirs="$subdirs Cgl"
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+echo "$as_me:$LINENO: checking whether project Alps is available" >&5
+echo $ECHO_N "checking whether project Alps is available... $ECHO_C" >&6
+
+coin_has_alps=notGiven
+coin_have_project_dir=no
+
+# check if user wants to skip project in any case
+
+if test x"$COIN_SKIP_PROJECTS" != x; then
+  for dir in $COIN_SKIP_PROJECTS; do
+    if test $dir = "Alps"; then
+      coin_has_alps=skipping
+    fi
+    if test $dir = "/Alps"; then
+      coin_has_alps=skipping
+    fi
+  done
+fi
+
+if test $coin_has_alps != skipping; then
+  if test $PACKAGE_TARNAME = alps; then
+    coin_has_alps=.
+    coin_have_project_dir=yes
+  fi
+
+
+# Check whether --with-m4_tolower(Alps)-lib or --without-m4_tolower(Alps)-lib was given.
+if test "${with_alps_lib+set}" = set; then
+  withval="$with_alps_lib"
+  coin_has_alps=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Alps)-incdir or --without-m4_tolower(Alps)-incdir was given.
+if test "${with_alps_incdir+set}" = set; then
+  withval="$with_alps_incdir"
+  coin_has_alps=installed
+fi;
+
+
+# Check whether --with-m4_tolower(Alps)-datadir or --without-m4_tolower(Alps)-datadir was given.
+if test "${with_alps_datadir+set}" = set; then
+  withval="$with_alps_datadir"
+  coin_has_alps=installed
+fi;
+
+
+
+
+
+fi
+
+if test $coin_has_alps = notGiven; then
+  #check for project by using pkg-config, if pkg-config is available
+  #we are only interested in installed packages here, so we do not search in $COIN_PKG_CONFIG_PATH_UNINSTALLED
+  if test -n "$PKG_CONFIG" ; then
+    coin_save_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
+    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH" ; export PKG_CONFIG_PATH
+
+if test -n "$PKG_CONFIG" ; then
+  if $PKG_CONFIG --exists "alps"; then
+    ALPS_VERSION=`$PKG_CONFIG --modversion "alps" 2>/dev/null`
+    coin_has_alps="$ALPS_VERSION"
+  else
+    ALPS_PKG_ERRORS=`$PKG_CONFIG $pkg_short_errors --errors-to-stdout --print-errors "alps"`
+
+  fi
+else
+  { { echo "$as_me:$LINENO: error: \"Cannot check for existance of module Alps without pkg-config\"" >&5
+echo "$as_me: error: \"Cannot check for existance of module Alps without pkg-config\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+    PKG_CONFIG_PATH="$coin_save_PKG_CONFIG_PATH"
+    export PKG_CONFIG_PATH
+  fi
+fi
+
+# if not found yet, check if project is available in present directory
+if test "$coin_has_alps" = notGiven; then
+  if test -d $srcdir//Alps; then
+    # If a third argument is given, then we have to check if one one the files given in that third argument is present.
+    # If none of the files in the third argument is available, then we consider the project directory as non-existing.
+    # However, if no third argument is given, then this means that there should be no check, and existence of the directory is sufficient.
+     coin_have_project_dir=yes
+
+    if test $coin_have_project_dir = yes; then
+      coin_has_alps=Alps
+    fi
+  fi
+fi
+
+echo "$as_me:$LINENO: result: $coin_has_alps" >&5
+echo "${ECHO_T}$coin_has_alps" >&6
+
+echo "$as_me:$LINENO: checking whether project Alps need to be configured" >&5
+echo $ECHO_N "checking whether project Alps need to be configured... $ECHO_C" >&6
+if test "$coin_have_project_dir" = yes ; then
+
+  if test -r $srcdir/Alps/configure; then
+    coin_subdirs="$coin_subdirs Alps"
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+
+subdirs="$subdirs Alps"
 
   else
     echo "$as_me:$LINENO: result: no" >&5
